import io
from datetime import datetime
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.pdfgen import canvas

# Premium Executive Color Palette
COLOR_NAVY = colors.HexColor("#0f172a")         # Slate-900 (Deep Executive Navy)
COLOR_PRIMARY = colors.HexColor("#0284c7")      # Sky-600 (Vibrant Brand Blue)
COLOR_PRIMARY_DARK = colors.HexColor("#0369a1") # Sky-700
COLOR_PRIMARY_LIGHT = colors.HexColor("#e0f2fe")# Sky-100
COLOR_EMERALD = colors.HexColor("#059669")      # Emerald-600
COLOR_EMERALD_LIGHT = colors.HexColor("#d1fae5")# Emerald-100
COLOR_AMBER = colors.HexColor("#d97706")        # Amber-600
COLOR_AMBER_LIGHT = colors.HexColor("#fef3c7")  # Amber-100
COLOR_SLATE_MUTED = colors.HexColor("#475569")  # Slate-600
COLOR_BG_LIGHT = colors.HexColor("#f8fafc")     # Slate-50
COLOR_BORDER = colors.HexColor("#cbd5e1")       # Slate-300
COLOR_BORDER_LIGHT = colors.HexColor("#e2e8f0") # Slate-200

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and stamp total page count on running headers/footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(COLOR_SLATE_MUTED)

        # Header on Pages 2+
        if self._pageNumber > 1:
            self.drawString(40, 755, "SMART CAREER PATH • EXECUTIVE CAREER BLUEPRINT")
            self.setFont("Helvetica", 8)
            self.drawRightString(572, 755, "CONFIDENTIAL & PROPRIETARY")
            self.setStrokeColor(COLOR_PRIMARY)
            self.setLineWidth(1)
            self.line(40, 747, 572, 747)

        # Footer on all pages
        self.setStrokeColor(COLOR_BORDER_LIGHT)
        self.setLineWidth(0.75)
        self.line(40, 42, 572, 42)

        self.setFont("Helvetica", 8)
        self.setFillColor(COLOR_SLATE_MUTED)
        self.drawString(40, 30, "Generated by Smart Career Path AI Engine • Personalized Career Intelligence Report")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.setFont("Helvetica-Bold", 8)
        self.drawRightString(572, 30, page_str)
        self.restoreState()

def build_executive_career_pdf(
    career: Dict[str, Any],
    user_name: str = "Candidate",
    profile: Optional[Dict[str, Any]] = None
) -> bytes:
    """
    Renders an Executive Career Blueprint PDF in pure Python via ReportLab.
    Page quantity is dynamic and driven by the depth of roadmap milestones, skills, and strategic plans.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=46,
        bottomMargin=46
    )

    styles = getSampleStyleSheet()
    
    # Custom Typography Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=COLOR_NAVY,
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        textColor=COLOR_PRIMARY,
        spaceAfter=10
    )

    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=COLOR_NAVY,
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=COLOR_NAVY
    )

    body_bold = ParagraphStyle(
        'CustomBodyBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )

    muted_style = ParagraphStyle(
        'CustomMuted',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=COLOR_SLATE_MUTED
    )

    story = []
    career_title = career.get('careerTitle') or career.get('title', 'Career Specialization Track')
    timeline_str = career.get('estimatedTimeline') or career.get('timeline', '6–12 months')
    salary_str = career.get('salaryRange', '$75,000 – $130,000 / yr')
    match_score = career.get('matchScore', 92)
    skills_list = career.get('requiredSkills') or career.get('skills', ['Problem Solving', 'System Design', 'Core Domain Competency'])
    learning_path = career.get('learningPath', [])
    description_text = career.get('description', 'Comprehensive career track focused on end-to-end technical mastery, systematic skill acquisition, and real-world production readiness.')

    today_date = datetime.now().strftime("%B %d, %Y")

    # =========================================================================
    # SECTION 1: EXECUTIVE COVER & PROFILE SNAPSHOT
    # =========================================================================
    
    # Top Header Badge
    header_table = Table([
        [
            Paragraph("<b>SMART CAREER PATH</b> • EXECUTIVE STRATEGY BRIEFING", ParagraphStyle('TopBadge', parent=subtitle_style, fontSize=9, textColor=COLOR_PRIMARY_DARK)),
            Paragraph(f"<b>Date:</b> {today_date}", ParagraphStyle('TopDate', parent=muted_style, alignment=2))
        ]
    ], colWidths=[380, 152])
    header_table.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, -1), 1.5, COLOR_PRIMARY),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 10))

    # Main Title & Role Subtitle
    story.append(Paragraph(f"{career_title}", title_style))
    story.append(Paragraph(f"Strategic Career Roadmap & Competency Masterplan for <b>{user_name}</b>", subtitle_style))
    story.append(Paragraph(description_text, body_style))
    story.append(Spacer(1, 10))

    # 4 Key Metrics Card
    metrics_data = [
        [
            Paragraph("<b>Candidate Profile</b>", body_bold),
            Paragraph(f"{user_name}", body_style),
            Paragraph("<b>Target Timeframe</b>", body_bold),
            Paragraph(f"{timeline_str}", body_style)
        ],
        [
            Paragraph("<b>Market Compensation</b>", body_bold),
            Paragraph(f"{salary_str}", ParagraphStyle('SalP', parent=body_style, textColor=COLOR_EMERALD)),
            Paragraph("<b>Strategic Match Score</b>", body_bold),
            Paragraph(f"<b>{match_score}% Compatibility</b>", ParagraphStyle('ScoreP', parent=body_style, textColor=COLOR_PRIMARY))
        ]
    ]
    t_metrics = Table(metrics_data, colWidths=[120, 146, 120, 146])
    t_metrics.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 1, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER_LIGHT),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_metrics)
    story.append(Spacer(1, 12))

    # Executive Placement Rationale
    story.append(Paragraph("Executive Placement Rationale", h1_style))
    story.append(Paragraph(
        f"• <b>Market Alignment:</b> {career_title} continues to experience sustained compound growth across enterprise, high-growth tech, and venture sectors globally.<br/>"
        f"• <b>Skill Bridge Potential:</b> Strong foundational correlation with analytical workflows, structured problem solving, and modern tool ecosystems.<br/>"
        f"• <b>Scalable Compensation:</b> Direct progression from entry associate bands into upper quartile leadership and staff-level compensation.<br/>"
        f"• <b>Autonomous Execution:</b> The sequential milestones outlined in this blueprint provide a deterministic path to production-grade competency.",
        body_style
    ))
    story.append(Spacer(1, 14))

    # =========================================================================
    # SECTION 2: PRIORITIZED COMPETENCY MATRIX & COMPENSATION
    # =========================================================================
    story.append(Paragraph("Section 2: Prioritized Competencies & Industry Compensation", h1_style))
    story.append(Paragraph(
        "A rigorous breakdown of core technical proficiencies, development targets, and real-world market compensation benchmarks.",
        body_style
    ))
    story.append(Spacer(1, 8))

    # Skills Table - Dynamic iteration over all skills
    skills_table_data = [
        [
            Paragraph("<b>Core Competency</b>", body_bold),
            Paragraph("<b>Skill Category</b>", body_bold),
            Paragraph("<b>Priority / Phase</b>", body_bold),
            Paragraph("<b>Proficiency Target</b>", body_bold)
        ]
    ]

    for i, s in enumerate(skills_list):
        priority_label = "Priority 1 (Phase 1)" if i < 3 else ("Priority 2 (Phase 2)" if i < 6 else "Priority 3 (Phase 3)")
        p_color = COLOR_PRIMARY if i < 3 else (COLOR_EMERALD if i < 6 else COLOR_AMBER)
        category_label = "Core Engine" if i < 2 else ("Architecture & Tooling" if i < 5 else "Domain Specialization")
        
        skills_table_data.append([
            Paragraph(f"<b>{s}</b>", body_style),
            Paragraph(category_label, muted_style),
            Paragraph(f"<font color='{p_color.hexval()}'><b>{priority_label}</b></font>", body_style),
            Paragraph("Production-Ready", muted_style)
        ])

    t_skills = Table(skills_table_data, colWidths=[150, 130, 130, 122])
    t_skills.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.75, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER_LIGHT),
        ('PADDING', (0, 0), (-1, -1), 4.5),
    ]))
    story.append(t_skills)
    story.append(Spacer(1, 12))

    # Compensation Breakdown
    story.append(Paragraph("Market Compensation Benchmarks by Seniority", h1_style))
    comp_data = [
        [Paragraph("<b>Seniority Band</b>", body_bold), Paragraph("<b>Experience</b>", body_bold), Paragraph("<b>Global Market Baseline</b>", body_bold), Paragraph("<b>Domestic / Regional (INR)</b>", body_bold)],
        [Paragraph("Entry / Associate", body_bold), Paragraph("0–2 Years", body_style), Paragraph("$60,000 – $90,000 / yr", body_style), Paragraph("₹6 – 12 LPA", body_style)],
        [Paragraph("Mid-Level Specialist", body_bold), Paragraph("2–5 Years", body_style), Paragraph("$95,000 – $140,000 / yr", body_style), Paragraph("₹14 – 28 LPA", body_style)],
        [Paragraph("Senior / Staff Lead", body_bold), Paragraph("5–8+ Years", body_style), Paragraph("$145,000 – $220,000+ / yr", body_style), Paragraph("₹30 – 55+ LPA", body_style)],
        [Paragraph("Principal Architect / Fellow", body_bold), Paragraph("8+ Years", body_style), Paragraph("$220,000 – $350,000+ / yr", ParagraphStyle('CompHi', parent=body_style, textColor=COLOR_EMERALD)), Paragraph("₹60 – 100+ LPA", ParagraphStyle('CompHi2', parent=body_style, textColor=COLOR_EMERALD))]
    ]
    t_comp = Table(comp_data, colWidths=[130, 90, 160, 152])
    t_comp.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.75, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER_LIGHT),
        ('PADDING', (0, 0), (-1, -1), 4.5),
    ]))
    story.append(t_comp)
    story.append(Spacer(1, 14))

    # =========================================================================
    # SECTION 3: SEQUENTIAL EXECUTION ROADMAP & DETAILED MILESTONES
    # =========================================================================
    story.append(Paragraph("Section 3: Sequential Execution Roadmap & Milestones", h1_style))
    story.append(Paragraph(
        "Structured, chronological milestones with procedures, deliverables, and vetted resources to systematically master each phase.",
        body_style
    ))
    story.append(Spacer(1, 8))

    default_steps = [
        {
            "order": 1,
            "title": "Core Theoretical Foundations & Environment Architecture",
            "duration": "Weeks 1–6",
            "description": "Establish deep syntactic, mathematical, and algorithmic fluency. Set up professional local environments, containerized runtimes, and version control.",
            "procedure": ["Set up modern IDE, Git workflows, and CLI tooling", "Master core language fundamentals, data structures, and algorithmic patterns", "Implement 5 foundational algorithmic projects from scratch"],
            "resources": ["CS50: Introduction to Computer Science", "The Pragmatic Programmer", "Official Documentation & Language Specs"]
        },
        {
            "order": 2,
            "title": "Intermediate Applied Systems & Modular Tooling",
            "duration": "Weeks 7–14",
            "description": "Design modular components, integrate RESTful APIs, interact with relational databases, and build test suites with CI/CD automation.",
            "procedure": ["Architect scalable database schemas and implement robust migrations", "Build and document high-performance REST and asynchronous endpoints", "Write comprehensive unit and integration tests (80%+ coverage)"],
            "resources": ["Designing Data-Intensive Applications", "Full Stack Open", "Docker & Kubernetes Official Guides"]
        },
        {
            "order": 3,
            "title": "Advanced Production Readiness & Complex Architectures",
            "duration": "Weeks 15–22",
            "description": "Engineer full-scale production capstone systems. Deploy to cloud infrastructure with zero-downtime workflows, caching, and observability.",
            "procedure": ["Implement distributed caching (Redis) and async task queues (Celery/Kafka)", "Deploy on AWS/GCP with automated GitHub Actions CI/CD pipelines", "Configure logging, Prometheus monitoring, and automated alerting"],
            "resources": ["System Design Primer (GitHub)", "AWS Well-Architected Framework", "Martin Fowler Architecture Patterns"]
        },
        {
            "order": 4,
            "title": "Portfolio Curation, System Design & Interview Mastery",
            "duration": "Weeks 23–28",
            "description": "Package production showcase applications, conduct technical mock interviews, publish technical articles, and target enterprise recruitment channels.",
            "procedure": ["Publish complete documented codebases and live demos on GitHub", "Complete 50+ targeted system design and problem-solving mock drills", "Execute targeted outreach to tech leads, mentors, and recruiters"],
            "resources": ["Cracking the Coding Interview", "Grokking the System Design Interview", "Tech Interview Handbook"]
        }
    ]

    active_steps = learning_path if (learning_path and len(learning_path) >= 1) else default_steps

    # Dynamically render ALL milestone stages in the learning roadmap without limit
    for step in active_steps:
        order = step.get("order", 1)
        stitle = step.get("title", f"Milestone {order}")
        duration = step.get("duration", "4–6 weeks")
        desc = step.get("description", "")
        procs = step.get("procedure", [])
        resources = step.get("resources", [])

        # Step block wrapped in KeepTogether so each milestone stays coherent
        step_elements = []
        step_header_data = [
            [
                Paragraph(f"<b>Stage {order}: {stitle}</b>", ParagraphStyle('StpH', parent=body_bold, textColor=COLOR_NAVY, fontSize=9.5)),
                Paragraph(f"<b>Timeline:</b> {duration}", ParagraphStyle('StpT', parent=muted_style, alignment=2))
            ]
        ]
        t_shead = Table(step_header_data, colWidths=[395, 137])
        t_shead.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), COLOR_PRIMARY_LIGHT),
            ('BOX', (0, 0), (-1, -1), 0.5, COLOR_PRIMARY),
            ('PADDING', (0, 0), (-1, -1), 3.5),
        ]))
        step_elements.append(t_shead)
        step_elements.append(Spacer(1, 3))

        if desc:
            step_elements.append(Paragraph(f"<b>Objective:</b> {desc}", body_style))
            step_elements.append(Spacer(1, 2))

        if procs:
            proc_text = "<br/>".join([f"  • {p}" for p in procs])
            step_elements.append(Paragraph(f"<b>Step-by-Step Procedure:</b><br/>{proc_text}", muted_style))
            step_elements.append(Spacer(1, 2))

        if resources:
            res_str = ", ".join(resources)
            step_elements.append(Paragraph(f"<b>Curated Learning Materials:</b> {res_str}", ParagraphStyle('ResP', parent=muted_style, textColor=COLOR_PRIMARY_DARK)))

        step_elements.append(Spacer(1, 8))
        story.append(KeepTogether(step_elements))

    story.append(Spacer(1, 10))

    # =========================================================================
    # SECTION 4: TACTICAL 30-60-90 DAY ACTION PLAN & CAREER TRAJECTORY
    # =========================================================================
    story.append(Paragraph("Section 4: Tactical 30-60-90 Day Plan & Career Trajectory", h1_style))
    story.append(Paragraph(
        "Immediate executable milestones to establish forward momentum, build credible portfolio assets, and execute market entry.",
        body_style
    ))
    story.append(Spacer(1, 8))

    # 30-60-90 Day Plan Table
    action_plan_data = [
        [
            Paragraph("<b>Phase</b>", body_bold),
            Paragraph("<b>Core Objectives & Deliverables</b>", body_bold),
            Paragraph("<b>Checkpoints</b>", body_bold)
        ],
        [
            Paragraph("<b>Days 1–30<br/>Foundations</b>", ParagraphStyle('P1', parent=body_style, textColor=COLOR_PRIMARY)),
            Paragraph("Set up dev workstation, configure CLI & Git. Finish core language certifications. Build 2 small CLI utilities with 90%+ test coverage.", body_style),
            Paragraph("• Dev env online<br/>• 2 repo commits / day<br/>• Core syntax exam", muted_style)
        ],
        [
            Paragraph("<b>Days 31–60<br/>Applied Practice</b>", ParagraphStyle('P2', parent=body_style, textColor=COLOR_EMERALD)),
            Paragraph("Engineer 2 full-stack end-to-end applications with database persistence, caching, and CI/CD pipelines. Write technical architecture documentation.", body_style),
            Paragraph("• 2 live deployed apps<br/>• Dockerized runtime<br/>• GitHub project boards", muted_style)
        ],
        [
            Paragraph("<b>Days 61–90<br/>Market Entry</b>", ParagraphStyle('P3', parent=body_style, textColor=COLOR_AMBER)),
            Paragraph("Polish GitHub portfolio, optimize LinkedIn profile for recruiter search algorithms, conduct 10 technical mock interviews, and submit 25 targeted applications.", body_style),
            Paragraph("• Polished portfolio<br/>• 10 mock drills<br/>• Active interview pipeline", muted_style)
        ]
    ]
    t_action = Table(action_plan_data, colWidths=[90, 310, 132])
    t_action.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.75, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER_LIGHT),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_action)
    story.append(Spacer(1, 12))

    # Dual-Track Career Progression
    story.append(Paragraph("Long-Term Dual-Track Career Trajectory", h1_style))
    trajectory_data = [
        [
            Paragraph("<b>Individual Contributor (IC) Track</b>", ParagraphStyle('IcT', parent=body_bold, textColor=COLOR_PRIMARY_DARK)),
            Paragraph("<b>Engineering Management Track</b>", ParagraphStyle('EmT', parent=body_bold, textColor=COLOR_EMERALD))
        ],
        [
            Paragraph("Junior Developer → Senior Engineer → Staff / Lead Architect → Principal Engineer → Technical Fellow", body_style),
            Paragraph("Tech Lead → Engineering Manager → Director of Engineering → VP of Technology → Chief Technology Officer (CTO)", body_style)
        ]
    ]
    t_traj = Table(trajectory_data, colWidths=[266, 266])
    t_traj.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.75, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER_LIGHT),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_traj)
    story.append(Spacer(1, 12))

    # Technical Interview & Ecosystem Checklist
    story.append(Paragraph("Technical Interview Strategy & Recommended Reading", h1_style))
    interview_text = (
        "• <b>System Design Strategy:</b> Focus on scalability, database sharding, latency mitigation, caching layers, and microservice decoupling.<br/>"
        "• <b>Behavioral Strategy:</b> Structure project anecdotes using the STAR framework (Situation, Task, Action, Result) with measurable metrics.<br/>"
        "• <b>Essential Literature:</b> <i>Designing Data-Intensive Applications</i> (Kleppmann), <i>The Pragmatic Programmer</i> (Thomas/Hunt), <i>High Output Management</i> (Grove).<br/>"
        "• <b>Recommended Communities:</b> GitHub Discussions, Stack Overflow Tech Hub, Discord Engineering Collectives, Kaggle Community."
    )
    story.append(Paragraph(interview_text, body_style))

    # Build document - dynamically generates as many pages as required
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
