import io
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

# Palette matching Next.js dark/light theme
COLOR_PRIMARY = colors.HexColor("#0284c7")       # Sky-600
COLOR_PRIMARY_DARK = colors.HexColor("#0369a1")  # Sky-700
COLOR_EMERALD = colors.HexColor("#059669")       # Emerald-600
COLOR_SLATE_DARK = colors.HexColor("#0f172a")    # Slate-900
COLOR_SLATE_MUTED = colors.HexColor("#475569")   # Slate-600
COLOR_BG_LIGHT = colors.HexColor("#f8fafc")      # Slate-50
COLOR_BORDER = colors.HexColor("#e2e8f0")        # Slate-200

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to calculate total page count for running footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(COLOR_SLATE_MUTED)

        # Header (Pages 2+)
        if self._pageNumber > 1:
            self.drawString(40, 762, "SMART CAREER PATH — EXECUTIVE CAREER BLUEPRINT")
            self.setStrokeColor(COLOR_BORDER)
            self.setLineWidth(0.5)
            self.line(40, 755, 572, 755)

        # Footer (All pages)
        self.setStrokeColor(COLOR_BORDER)
        self.setLineWidth(0.5)
        self.line(40, 42, 572, 42)

        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawString(40, 30, "Confidential Career Guidance Document • Generated by Smart Career Path AI")
        self.drawRightString(572, 30, page_str)
        self.restoreState()

def build_executive_career_pdf(
    career: Dict[str, Any],
    user_name: str = "Candidate",
    profile: Optional[Dict[str, Any]] = None
) -> bytes:
    """
    Renders an Executive 4-Page Career Blueprint PDF in pure Python via ReportLab.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=50,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()
    
    # Custom Typography Styles
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=COLOR_SLATE_DARK,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=COLOR_PRIMARY,
        spaceAfter=14
    )

    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=COLOR_SLATE_DARK,
        spaceBefore=8,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=COLOR_SLATE_DARK
    )

    muted_style = ParagraphStyle(
        'CustomMuted',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=COLOR_SLATE_MUTED
    )

    story = []

    # ==========================================
    # PAGE 1: EXECUTIVE COVER & PROFILE SNAPSHOT
    # ==========================================
    story.append(Paragraph("EXECUTIVE CAREER BLUEPRINT", subtitle_style))
    story.append(Paragraph(f"{career.get('careerTitle', 'Career Track')}", title_style))
    story.append(Paragraph(career.get('description', ''), body_style))
    story.append(Spacer(1, 14))

    # Metric Highlight Grid
    metrics_data = [
        [
            Paragraph(f"<b>Candidate:</b> {user_name}", body_style),
            Paragraph(f"<b>Est. Timeline:</b> {career.get('estimatedTimeline', '6–12 months')}", body_style)
        ],
        [
            Paragraph(f"<b>Market Compensation:</b> {career.get('salaryRange', 'Competitive')}", body_style),
            Paragraph(f"<b>Match Confidence:</b> {career.get('matchScore', 85)}%", body_style)
        ]
    ]
    t_metrics = Table(metrics_data, colWidths=[260, 260])
    t_metrics.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 1, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(t_metrics)
    story.append(Spacer(1, 20))

    # Table of Contents Box
    story.append(Paragraph("Blueprint Roadmap Architecture", h1_style))
    toc_data = [
        [Paragraph("<b>Section 1:</b> Strategic Foundations & Role Profile", body_style), Paragraph("Page 1", muted_style)],
        [Paragraph("<b>Section 2:</b> Prioritized Skills Matrix & Compensation Levels", body_style), Paragraph("Page 2", muted_style)],
        [Paragraph("<b>Section 3:</b> Sequential Learning Roadmap & Milestones", body_style), Paragraph("Page 3", muted_style)],
        [Paragraph("<b>Section 4:</b> Trajectory, 30-60-90 Plan & Ecosystem Resources", body_style), Paragraph("Page 4", muted_style)],
    ]
    t_toc = Table(toc_data, colWidths=[450, 70])
    t_toc.setStyle(TableStyle([
        ('BOX', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_toc)
    story.append(Spacer(1, 20))

    # Why Recommended
    reasons = career.get("whyRecommended", [])
    if reasons:
        story.append(Paragraph("Strategic Alignment & Placement Rationale", h1_style))
        for r in reasons[:4]:
            story.append(Paragraph(f"• {r}", body_style))
            story.append(Spacer(1, 3))

    story.append(PageBreak())

    # ==========================================
    # PAGE 2: SKILLS MATRIX & COMPENSATION
    # ==========================================
    story.append(Paragraph("Section 2: Comprehensive Skills Matrix & Market Compensation", h1_style))
    story.append(Paragraph(
        "A rigorous breakdown of technical competencies, prioritized by industry demand, paired with compensation benchmarks.",
        body_style
    ))
    story.append(Spacer(1, 10))

    # Skills Table
    req_skills = career.get("requiredSkills", ["Problem Solving", "System Architecture", "Communication"])
    matching = career.get("matchingSkills", [])
    develop = career.get("skillsToDevelop", req_skills)

    skills_table_data = [
        [Paragraph("<b>Skill Category</b>", body_style), Paragraph("<b>Key Competencies</b>", body_style), Paragraph("<b>Status</b>", body_style)]
    ]
    for s in req_skills[:7]:
        status = "Verified Match" if s in matching else "Development Target"
        status_color = COLOR_EMERALD if s in matching else COLOR_PRIMARY
        skills_table_data.append([
            Paragraph("Core Competency", body_style),
            Paragraph(s, body_style),
            Paragraph(f"<font color='{status_color.hexval()}'><b>{status}</b></font>", body_style)
        ])

    t_skills = Table(skills_table_data, colWidths=[140, 260, 120])
    t_skills.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_skills)
    story.append(Spacer(1, 18))

    # Compensation Tiers
    story.append(Paragraph("Market Compensation & Career Tiers", h1_style))
    comp_data = [
        [Paragraph("<b>Seniority Level</b>", body_style), Paragraph("<b>Experience</b>", body_style), Paragraph("<b>Estimated Range</b>", body_style)],
        [Paragraph("Entry / Associate", body_style), Paragraph("0–2 Years", body_style), Paragraph("Entry: $55,000 – $85,000 / yr (6–12 LPA)", body_style)],
        [Paragraph("Mid-Level Professional", body_style), Paragraph("2–5 Years", body_style), Paragraph("Mid: $90,000 – $135,000 / yr (14–26 LPA)", body_style)],
        [Paragraph("Senior / Staff Lead", body_style), Paragraph("5–8+ Years", body_style), Paragraph("Senior: $140,000 – $220,000+ / yr (28–50+ LPA)", body_style)],
    ]
    t_comp = Table(comp_data, colWidths=[150, 120, 250])
    t_comp.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_comp)

    story.append(PageBreak())

    # ==========================================
    # PAGE 3: SEQUENTIAL LEARNING ROADMAP
    # ==========================================
    story.append(Paragraph("Section 3: Sequential Execution Roadmap", h1_style))
    story.append(Paragraph(
        "Structured, chronological milestones designed to take you from core foundations to production-level competency.",
        body_style
    ))
    story.append(Spacer(1, 10))

    learning_path = career.get("learningPath", [])
    for step in learning_path[:4]:
        order = step.get("order", 1)
        title = step.get("title", f"Milestone {order}")
        duration = step.get("duration", "2–3 months")
        desc = step.get("description", "")
        procs = step.get("procedure", [])
        resources = step.get("resources", [])

        step_content = [
            [
                Paragraph(f"<b>Stage {order}: {title}</b>", ParagraphStyle('StepH', parent=body_style, fontName='Helvetica-Bold', textColor=COLOR_PRIMARY_DARK)),
                Paragraph(f"<b>Timeline:</b> {duration}", muted_style)
            ]
        ]
        t_step_head = Table(step_content, colWidths=[400, 120])
        t_step_head.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), COLOR_BG_LIGHT),
            ('BOX', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(t_step_head)
        story.append(Spacer(1, 4))

        if desc:
            story.append(Paragraph(desc, body_style))
            story.append(Spacer(1, 3))

        for p in procs[:3]:
            story.append(Paragraph(f"  • {p}", muted_style))
            story.append(Spacer(1, 2))

        if resources:
            story.append(Paragraph(f"<b>Recommended Resources:</b> {', '.join(resources[:4])}", muted_style))

        story.append(Spacer(1, 12))

    story.append(PageBreak())

    # ==========================================
    # PAGE 4: TRAJECTORY & 30-60-90 DAY PLAN
    # ==========================================
    story.append(Paragraph("Section 4: Strategic 30-60-90 Day Action Plan", h1_style))
    story.append(Paragraph(
        "Immediate practical actions to build momentum and achieve verifiable milestones in your first quarter.",
        body_style
    ))
    story.append(Spacer(1, 8))

    action_plan_data = [
        [
            Paragraph("<b>Days 1–30: Foundations</b>", body_style),
            Paragraph("Complete core courses, establish study cadence, set up local developer/work environment, and build initial small exercises.", muted_style)
        ],
        [
            Paragraph("<b>Days 31–60: Deep Practice</b>", body_style),
            Paragraph("Build 2 end-to-end practical projects demonstrating practical skills. Write clean documentation and commit progress to GitHub/portfolio.", muted_style)
        ],
        [
            Paragraph("<b>Days 61–90: Portfolio & Outreach</b>", body_style),
            Paragraph("Package showcase projects, optimize LinkedIn/resume, conduct mock interviews, and initiate active outreach to mentors and hiring managers.", muted_style)
        ]
    ]
    t_action = Table(action_plan_data, colWidths=[160, 360])
    t_action.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), COLOR_BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('PADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(t_action)
    story.append(Spacer(1, 16))

    story.append(Paragraph("Long-Term Career Trajectory", h1_style))
    trajectory_text = (
        "<b>Individual Contributor Track:</b> Junior Specialist → Lead Practitioner → Principal Architect → Technical Fellow.<br/>"
        "<b>Management Track:</b> Team Lead → Engineering / Functional Manager → Director → VP / Department Head."
    )
    story.append(Paragraph(trajectory_text, body_style))
    story.append(Spacer(1, 14))

    story.append(Paragraph("Ecosystem Books & Communities", h1_style))
    story.append(Paragraph(
        "• Recommended Reading: High-Output Management, The Pragmatic Programmer, Designing Data-Intensive Applications.<br/>"
        "• Professional Communities: GitHub Discussions, Stack Overflow, Discord Tech Hubs, Kaggle Community.",
        muted_style
    ))

    # Build document with custom canvas
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
